feat: 支持制品加密存储 #992
TencentBlueKing/bk-repo pull request #1028
Opened 2023-08-03 08:07 UTC by felixncheng

2023-08-04 07:42 UTC, zacYL approved these changes

2023-08-07 03:51 UTC, cnlkl requested changes

2023-08-07 03:51 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/AbstractEncryptorFileStorage.kt
> +            inputStream.use { input ->
这边流是不是不用在这里关闭，谁创建的谁关闭

2023-08-07 03:53 UTC, cnlkl requested changes

2023-08-07 03:53 UTC, cnlkl commented on src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/model/TNode.kt
> +    var encryptedSha256: String? = null,
这个字段现在有使用吗

2023-08-07 03:53 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/AbstractEncryptorFileStorage.kt
> +            return super.load(path, name, range, storageCredentials)
这边是不是不允许部分制品加密，部分不加密，系统部署后就再也不能改这个配置项了

2023-08-10 09:26 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/AbstractEncryptorFileStorage.kt
> +            return super.load(path, name, range, storageCredentials)
加密是按存储实例颗粒度来的。
加密存储和普通存储是隔离开的，如果修改这个配置选项，那么之前的存储就失效了。

2023-08-10 12:59 UTC, cnlkl approved these changes

2023-08-10 13:22 UTC, merged