bug:仓库树tooltip展示错误 #1066
TencentBlueKing/bk-repo pull request #1070
Opened 2023-08-16 02:56 UTC by lannoy0523

2023-08-16 06:52 UTC, cnlkl requested changes

2023-08-16 06:52 UTC, cnlkl commented on src/frontend/devops-repository/src/components/RepoTree/index.vue
> +                        <div class="mr10 node-text" v-html="importantTransform(item.displayName)" v-bk-tooltips="{ content: item.displayName || item.name, placements: ['top'], disabled: (item.display
这里`displayName`不存在的时候调用它的`toString`方法会不会导致错误

2023-08-16 07:29 UTC, lannoy0523 commented on src/frontend/devops-repository/src/components/RepoTree/index.vue
> +                        <div class="mr10 node-text" v-html="importantTransform(item.displayName)" v-bk-tooltips="{ content: item.displayName || item.name, placements: ['top'], disabled: (item.display
这里插入的html的条件就是displayName，这里displayName不会不存在。

2023-08-17 05:55 UTC, gujunling approved these changes

2023-08-17 05:55 UTC, gujunling commented on src/frontend/devops-repository/src/components/RepoTree/index.vue
> +                        <div class="mr10 node-text" v-html="importantTransform(item.displayName)" :title="item.displayName > 19 && openType === '' ? item.displayName : ''"></div>
:title="(item.displayName || '').length > 19 && openType === '' ? item.displayName : ''"

2023-08-17 05:58 UTC, gujunling approved these changes

2023-08-18 02:13 UTC, merged