feat: 支持OpenId Connect协议 #964
TencentBlueKing/bk-repo pull request #1075
Opened 2023-08-17 12:30 UTC by yaoxuwan

2023-08-30 02:26 UTC, cnlkl requested changes

2023-08-30 02:26 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/resources/templates/authorize.ftl
> +    <p>请授权应用${appId}申请访问您(${userId})的帐户:</p>
1. 这里要不要做一下国际化
2. 要不要把应用具体申请了哪些权限也展示出来

2023-09-04 07:25 UTC, owenlxu approved these changes

2023-09-04 07:26 UTC, cnlkl approved these changes

2023-09-04 08:24 UTC, merged