支持制品加固和下载请求转发
TencentBlueKing/bk-repo pull request #1108
Opened 2023-08-30 03:38 UTC by felixncheng

2023-09-06 04:16 UTC, cnlkl requested changes

2023-09-06 04:16 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/ScanController.kt
> +            tokenService.checkToken(subtaskId, token)
这里通过deployment模式扫描时，`subtaskId`是`executionClusterName`，应该要再单独加一个校验方法

2023-09-11 08:03 UTC, felixncheng commented on src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/utils/DockerUtils.kt
> +                        .withUsername(userName)
已修改

2023-09-11 08:04 UTC, felixncheng commented on src/backend/common/common-analysis/src/main/kotlin/com/tencent/bkrepo/common/analysis/pojo/scanner/trivy/TrivyScanner.kt
> +    val dockerRegistryPassword: String?,
经测试，不添加默认值是可以被反序列化的，反序列化的值为null

2023-09-11 08:11 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/ScanController.kt
> +            tokenService.checkToken(subtaskId, token)
#1149

2023-09-11 08:12 UTC, felixncheng commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/ScanController.kt
> +            tokenService.checkToken(subtaskId, token)
暂时不需要

2023-09-12 02:43 UTC, merged