支持git proxy
TencentBlueKing/bk-repo pull request #1159
Opened 2023-09-12 13:37 UTC by felixncheng

2023-09-13 02:35 UTC, cnlkl approved these changes

2023-09-13 02:35 UTC, cnlkl commented on src/backend/git/biz-git/src/main/kotlin/com/tencent/bkrepo/git/interceptor/devx/DevxSrcIpInterceptor.kt
> +        val workspace_name: String,
变量命名不符合规范

2023-09-20 03:31 UTC, cnlkl requested changes

2023-09-20 03:31 UTC, cnlkl commented on src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/RepoTypeRuleInterceptor.kt
> +            val repoNameList = repositoryService.listRepo(projectId, name = null, type = value.toString(), true)
这里display固定传true，是不是就没办法查询所有仓库了

2023-09-20 06:47 UTC, felixncheng commented on src/backend/git/biz-git/src/main/kotlin/com/tencent/bkrepo/git/interceptor/devx/DevxSrcIpInterceptor.kt
> +        val workspace_name: String,
这里只是方便json转换，有更好的办法吗

2023-09-20 06:48 UTC, felixncheng commented on src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/search/common/RepoTypeRuleInterceptor.kt
> +            val repoNameList = repositoryService.listRepo(projectId, name = null, type = value.toString(), true)
true就是查询非false，包含空。跟之前是一样的。

2023-09-21 02:08 UTC, cnlkl approved these changes

2023-09-21 03:21 UTC, cnlkl approved these changes

2023-09-21 03:24 UTC, merged