feat: fs-server支持客户端会话管理 #1275
TencentBlueKing/bk-repo pull request #1288
Opened 2023-10-17 11:41 UTC by yaoxuwan

2023-10-18 07:07 UTC, cnlkl requested changes

2023-10-18 07:07 UTC, cnlkl commented on src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/service/ClientService.kt
> +        val client = clientRepository.findOne(query)
这里可以直接update，不用查出来再更新

2023-10-18 07:07 UTC, cnlkl commented on src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/handler/ClientHandler.kt
> +        val clientId = request.pathVariable("clientId")
这边参数只有client，怎么做鉴权

2023-10-18 07:07 UTC, cnlkl commented on src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/FsClientController.kt
> +    @GetMapping("/list")
这个接口为什么要放opdata服务

2023-10-18 07:46 UTC, yaoxuwan commented on src/backend/fs/boot-fs-server/src/main/kotlin/com/tencent/bkrepo/fs/server/service/ClientService.kt
> +            val client = clientRepository.findOne(query)
upsert还是需要再查一次，获取到id

2023-10-18 07:54 UTC, yaoxuwan commented on src/backend/opdata/biz-opdata/src/main/kotlin/com/tencent/bkrepo/opdata/controller/FsClientController.kt
> +    @GetMapping("/list")
打算做到admin里

2023-10-19 03:25 UTC, cnlkl approved these changes

2023-10-19 11:51 UTC, merged