feat: 增加镜像仓库清理job #1368
TencentBlueKing/bk-repo pull request #1383
Opened 2023-11-03 04:00 UTC by zacYL

2023-11-07 01:59 UTC, yaoxuwan approved these changes

2023-11-08 06:50 UTC, yaoxuwan approved these changes

2023-11-08 07:35 UTC, cnlkl requested changes

2023-11-08 07:35 UTC, cnlkl commented on docs/apidoc/repo/repository.md
> +          "cleanupStrategy":{
这个是settings里的字段吧

2023-11-08 07:35 UTC, cnlkl commented on src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/ArtifactCleanupJob.kt
> +        if (properties.projectList.isNotEmpty() && !properties.projectList.contains(projectId)) return false
这边是不是有项目要清理就要手动到配置里面加一下，项目和仓库也没有绑定，是分别判断的

2023-11-08 07:47 UTC, zacYL commented on src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/ArtifactCleanupJob.kt
> +        if (properties.projectList.isNotEmpty() && !properties.projectList.contains(projectId)) return false
这个只是job 中的特殊配置， 正常只需要 repo的 config 加上就可以， 默认是不填的

2023-11-08 07:51 UTC, zacYL commented on docs/apidoc/repo/repository.md
> +          "cleanupStrategy":{
文档已调整

2023-11-08 09:28 UTC, cnlkl approved these changes

2023-11-09 02:56 UTC, merged