fix: 创建分发计划时cron表达式的英文翻译有误 #1403
TencentBlueKing/bk-repo pull request #1404
Opened 2023-11-07 11:00 UTC by gujunling

2023-11-07 11:40 UTC, cnlkl requested changes

2023-11-07 11:40 UTC, cnlkl commented on src/frontend/devops-repository/src/main.js
> +Vue.prototype.currentLanguage = cookies.get('blueking_language') || 'zh-cn'
这边切换语言的时候需要更新`Vue.prototype.currentLanguage`

2023-11-08 01:36 UTC, gujunling commented on src/frontend/devops-repository/src/main.js
> +Vue.prototype.currentLanguage = cookies.get('blueking_language') || 'zh-cn'
切换语言时会自动刷新当前页面的，此时又会从main.js这个入口文件开始执行，所以这个语言是会改变的

2023-11-08 01:42 UTC, cnlkl approved these changes

2023-11-15 07:21 UTC, merged