fix: Lfs仓库缓存文件Http响应未关闭 #1353
TencentBlueKing/bk-repo pull request #1424
Opened 2023-11-09 08:20 UTC by yaoxuwan

2023-11-11 02:29 UTC, cnlkl approved these changes

2023-11-11 02:40 UTC, cnlkl requested changes

2023-11-11 02:40 UTC, cnlkl commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/security/RemoteAuthHandler.kt
> +        return authCredentials.username
这边未做校验直接允许设置任何用户，可能存在越权风险

2023-11-11 03:04 UTC, yaoxuwan commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/security/RemoteAuthHandler.kt
> +        return authCredentials.username
远程仓库凭证直接传递到远程代码库，由代码库认证鉴权

2023-11-15 01:55 UTC, cnlkl commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/security/RemoteAuthHandler.kt
> +        return authCredentials.username
本地lfs仓库也会经过这个AuthHandler，而且这边似乎不需要一定是LFS仓库，其他仓库也可以通过LFS的接口访问

2023-11-15 02:25 UTC, yaoxuwan commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/security/RemoteAuthHandler.kt
> +        return authCredentials.username
本地lfs会直接返回AnonymousCredentials。其他仓库可以访问接口，但是local仓库也需要鉴权

2023-11-15 07:08 UTC, cnlkl approved these changes

2023-11-17 01:44 UTC, merged