feat: 制品库支持深度归档 #1340
TencentBlueKing/bk-repo pull request #1432
Opened 2023-11-13 02:28 UTC by felixncheng

2023-11-17 14:19 UTC, cnlkl requested changes

2023-11-17 14:19 UTC, cnlkl commented on src/backend/archive/biz-archive/src/main/kotlin/com/tencent/bkrepo/archive/service/ArchiveServiceImpl.kt
> +    private val archiveMetrics: ArchiveMetrics,
未使用的变量

2023-11-17 14:19 UTC, cnlkl commented on src/backend/archive/biz-archive/src/main/kotlin/com/tencent/bkrepo/archive/service/ArchiveServiceImpl.kt
> +                val key = "${sha256}$XZ_SUFFIX"
这里key一定是.xz后缀吗

2023-11-17 14:19 UTC, cnlkl commented on src/backend/archive/biz-archive/src/main/kotlin/com/tencent/bkrepo/archive/repository/ReactiveArchiveFileDao.kt
> +class ReactiveArchiveFileDao : SimpleMongoReactiveDao<TArchiveFile>()
这个类未使用

2023-11-20 03:28 UTC, felixncheng commented on src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/IdleNodeArchiveJob.kt
> +    private val nodeUseInfoCache = ConcurrentHashMap<NodeDataId, Boolean>()
每次任务结束会clear

2023-11-20 03:29 UTC, felixncheng commented on src/backend/job/biz-job/src/main/kotlin/com/tencent/bkrepo/job/batch/IdleNodeArchiveJob.kt
> +        lastCutoffTime = tempCutoffTime
这里tempCutoffTime是build的query的时间，执行不在范围内。

2023-11-20 03:30 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/sign/CosSigner.kt
> +    private fun buildPublicFormatString(request: CosRequest): String {
不一样，一个是/r/n一个是/n，另外新加的签名是最后要补一个/n

2023-11-20 03:35 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/innercos/endpoint/PublicCosInnerEndpointBuilder.kt
> +        return "$bucket.cos-internal.$region.tencentcos.cn"
感觉可以保留吧，如果不是部署在腾讯云，这里就派上用场了

2023-11-20 03:41 UTC, felixncheng commented on src/backend/build.gradle.kts
> +            dependency("org.tukaani:xz:${Versions.XzJava}")
我去掉这里的引用吧，这个依赖不在核心路径

2023-11-20 04:18 UTC, cnlkl approved these changes

2023-11-21 02:03 UTC, felixncheng commented on src/backend/archive/biz-archive/src/main/kotlin/com/tencent/bkrepo/archive/service/ArchiveServiceImpl.kt
> +                val key = "${sha256}$XZ_SUFFIX"
目前是的

2023-11-21 02:46 UTC, cnlkl approved these changes

2023-11-21 02:49 UTC, merged