generic类型制品支持S3协议获取 #1296
TencentBlueKing/bk-repo pull request #1457
Opened 2023-11-17 02:45 UTC by liuliaozhong

2023-11-24 10:09 UTC, ccxwhy commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/S3MessageCode.kt
这里统一规范，实现MessageCode接口，在模块内去定义该类，定义自己的业务码和模块码

2023-11-24 10:12 UTC, ccxwhy commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/exception/AWS4AuthenticationException.kt
业务异常定义可以去继承ErrorCodeException，有更明确的异常定义范围，方便后续处理

2023-11-24 10:18 UTC, ccxwhy commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/exception/S3NotFoundException.kt
同上一条评论

2023-11-26 08:03 UTC, liuliaozhong commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/S3MessageCode.kt
已处理，实现了MessageCode，已在模块内定义

2023-11-26 08:03 UTC, liuliaozhong commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/exception/AWS4AuthenticationException.kt
已改

2023-11-26 08:04 UTC, liuliaozhong commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/exception/S3NotFoundException.kt
已改

2023-11-29 07:40 UTC, ccxwhy commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/aws4/AWS4AuthHandler.kt
> +                var password: String? = authenticationManager.findUserPwd(userName)
注意代码规范，这里返回值为null就抛异常了，所以返回值不用带问号，下面也不用进行强转

2023-11-29 09:09 UTC, ccxwhy commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3ObjectArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.GENERIC
这里会和Generic模块冲突，在动态注册bean时这里会覆盖generic仓库配置，对单体打包时对generic模块有影响

2023-11-29 09:11 UTC, ccxwhy commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/response/S3ArtifactResourceWriter.kt
DefaultArtifactResourceWriter是ArtifactResourceWriter的默认实现类，要对该类进行重写请实现ArtifactResourceWriter类

2023-11-29 09:20 UTC, ccxwhy commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +    private val localRepository: S3LocalRepository,
这里的bean在父类已经定义过了，在这里没必要注入

2023-11-29 09:22 UTC, ccxwhy commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +    fun getObject(artifactInfo: S3ObjectArtifactInfo) {
这里逻辑与generic仓库类似，是否可以复用？相关操作在父类都有对应实现，可以考虑进行复用

2023-11-29 09:27 UTC, ccxwhy commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/S3ErrorTypes.kt
常量类不用定义成object，业务模块相关常量不要写在公共模块中

2023-11-29 09:33 UTC, ccxwhy commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/aws4/AWS4AuthCredentials.kt
如果成员变量后续不用修改使用val定义

2023-11-29 09:34 UTC, ccxwhy commented on src/backend/buildSrc/src/main/kotlin/Versions.kt
注意大小写规范

2023-11-29 09:36 UTC, ccxwhy commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/util/AWS4AuthUtil.kt
考虑复用一些公共方法，对应的方法也可以进行抽取

2023-12-05 03:06 UTC, cnlkl requested changes

2023-12-05 03:06 UTC, cnlkl commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/AutoIndexRepositorySettings.kt
> +data class AutoIndexRepositorySettings(
这里和generic里的类重复了，可以考虑加个common-generic模块放s3和generic的公共类

2023-12-05 07:29 UTC, cnlkl requested changes

2023-12-05 07:29 UTC, cnlkl commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/controller/S3ObjectController.kt
> +        val parts = decodedBucketName.split(".")
这里projectId和repoName能不能放到url里

2023-12-08 12:44 UTC, liuliaozhong commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/aws4/AWS4AuthHandler.kt
> +                var password: String? = authenticationManager.findUserPwd(userName)
已修改

2023-12-08 12:45 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3ObjectArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.GENERIC
改成NONE了，不影响功能

2023-12-08 12:45 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3ObjectArtifactConfigurer.kt
> +    fun artifactResourceWriter(storageProperties: StorageProperties): ArtifactResourceWriter {
已改

2023-12-08 12:46 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +    private val localRepository: S3LocalRepository,
已改

2023-12-08 12:47 UTC, liuliaozhong commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/S3ErrorTypes.kt
已改

2023-12-08 12:47 UTC, liuliaozhong commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/exception/GlobalExceptionHandler.kt
> +    @ExceptionHandler(AWS4AuthenticationException::class)
已调整

2023-12-08 12:47 UTC, liuliaozhong commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/util/S3ExceptionCommonResponse.kt
> +            response.addHeader(HttpHeaders.SERVER, HttpContextHolder.getClientAddress())
不是必要的，去掉了

2023-12-08 12:48 UTC, liuliaozhong commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/message/CommonMessageCode.kt
> +    REQUEST_SIGNANOTMATC("system.request.sign.not-match"),
已调整

2023-12-08 12:48 UTC, liuliaozhong commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/HttpAuthSecurityConfiguration.kt
> +            httpAuthSecurity.addHttpAuthHandler(AWS4AuthHandler(authenticationManager))
已调整

2023-12-08 12:48 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/response/S3ArtifactResourceWriter.kt
> +        response.setHeader("x-amz-request-id", getTraceId())
已优化

2023-12-08 12:50 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/S3LocalRepository.kt
> +    override fun onDownloadBefore(context: ArtifactDownloadContext) {
子类移除了，用父类中默认实现

2023-12-08 12:51 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +                ?: throw ErrorCodeException(ArtifactMessageCode.REPOSITORY_NOT_FOUND, repoName)
已改

2023-12-08 12:51 UTC, liuliaozhong commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/util/AWS4AuthUtil.kt
> +    fun validAuthorization(
已优化

2023-12-08 12:51 UTC, liuliaozhong commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/aws4/AWS4AuthHandler.kt
> +                buildAWS4AuthorizationInfo(request, userName, password!!)
已优化

2023-12-08 12:54 UTC, liuliaozhong commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/aws4/AWS4AuthHandler.kt
> +                var password: String? = authenticationManager.findUserPwd(userName)
Access Key，Secret Key在客户端必填，单用token认证在客户端会缺少必填参数，这块逻辑没改

2023-12-08 12:55 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/controller/S3ObjectController.kt
> +        val parts = decodedBucketName.split(".")
已修改，与其他模块一致，{project}/{repoName}形式

2023-12-13 02:23 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/auth/AWS4AuthHandler.kt
> +            accessKeyId = accessKeyId,
这几个 header 如果不存在则会抛异常

2023-12-13 02:34 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3RegistryArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.NONE
如果此处设置为 NONE, ArtifactContextHolder中queryRepoDetail会根据projectId，repoName, getRepositoryType()三个参数去获取对应仓库信息. 那你建仓库的时候建的是什么类型的仓库呢？

2023-12-13 03:07 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3RegistryArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.NONE
建的generic类型仓库，NONE这样可以吗？如果RepositoryType.GENERIC，单体打包时对generic模块会有影响

2023-12-13 03:35 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/response/S3ExceptionCommonResponse.kt
> +            response.setCharacterEncoding("utf-8")
像这些可以使用现成的常量

2023-12-13 03:44 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/utils/AWS4AuthUtil.kt
> +        println("new: hashedCanonicalRequest: $hashedCanonicalRequest")
这个打印是否可以去掉

2023-12-13 04:10 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +            ArtifactContextHolder.getRepoDetail()
这段代码是不是多余的

2023-12-13 04:11 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +                    HttpStatus.NOT_FOUND,
仓库找不到应该抛出仓库找不到异常

2023-12-13 09:06 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +                    HttpStatus.NOT_FOUND,
这里抛出这个异常是否合适

2023-12-13 09:10 UTC, zacYL commented on src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/resolve/response/BaseArtifactResourceHandler.kt
> +                recordAbleInputStream.rateLimit(responseRateLimitWrapper(storageProperties.response.rateLimit)).use {
这个类抽象出来是解决什么问题？

2023-12-13 09:17 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +                    HttpStatus.NOT_FOUND,
ArtifactContextHolder里会去校验仓库是否存在，不用再重复检验了

2023-12-13 09:18 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +            val context = ArtifactDownloadContext(repo = repo, artifact = artifactInfo)
这里其实也不用传 repo, artifact， 会自动从request中去获取

2023-12-13 09:20 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3RegistryArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.NONE
> 建的generic类型仓库，NONE这样可以吗？如果RepositoryType.GENERIC，单体打包时对generic模块会有影响

当你请求走到 s3 服务时， 会根据projectId，repoName,NONE 去查询仓库信息，肯定查不到啊

2023-12-13 11:48 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3RegistryArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.NONE
这个地方应该怎么做呢？
从代码上看没问题吧，如果type是NONE，查询时会移除type条件，逻辑如下：
if (repoType != null && repoType.toUpperCase() != RepositoryType.NONE.name) {
    criteria.and(TRepository::type).isEqualTo(repoType.toUpperCase())
}

2023-12-13 11:59 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/response/S3ExceptionCommonResponse.kt
> +            response.setCharacterEncoding("utf-8")
这几个没有现成的常量，添加到HttpHeaders对象里吧

2023-12-14 05:46 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/auth/AWS4AuthHandler.kt
> +            accessKeyId = accessKeyId,
已修改

2023-12-14 05:46 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3RegistryArtifactConfigurer.kt
> +    override fun getRepositoryType() = RepositoryType.NONE
已修改，主类型S3, 辅类型为GENERIC

2023-12-14 05:47 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/utils/AWS4AuthUtil.kt
> +        println("new: hashedCanonicalRequest: $hashedCanonicalRequest")
多余的，已去掉

2023-12-14 05:54 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +                    HttpStatus.NOT_FOUND,
改成没权限一样了

2023-12-14 05:54 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +                    HttpStatus.NOT_FOUND,
去掉了

2023-12-14 05:54 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +            ArtifactContextHolder.getRepoDetail()
ArtifactContextHolder.getRepoDetail()要的，不然request.getAttribute(REPO_KEY)为null

2023-12-14 05:54 UTC, liuliaozhong commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/service/S3ObjectService.kt
> +            val context = ArtifactDownloadContext(repo = repo, artifact = artifactInfo)
移除了

2023-12-20 08:43 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/S3LocalRepository.kt
> +        } catch (exception: Exception) {
download函数有对应异常捕获以及 finally处理，此处不需要

2023-12-20 08:51 UTC, cnlkl requested changes

2023-12-20 08:51 UTC, cnlkl commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/Constants.kt
> +const val AWS4_AUTH_PREFIX = "AWS4-HMAC-SHA256 "
S3的常量需要移到S3模块

2023-12-20 08:51 UTC, cnlkl commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/constant/HttpHeaders.kt
> +    const val X_AMZ_TRACE_ID = "X-Amz-Trace-Id"
只有S3用到的header可以放到S3模块中

2023-12-20 08:51 UTC, cnlkl commented on src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/resolve/response/BaseArtifactResourceHandler.kt
> +open class BaseArtifactResourceHandler(
这个可以改成抽象类，继承`ArtifactResourceWriter`接口

2023-12-20 08:51 UTC, cnlkl commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/configuration/S3RegistryArtifactConfigurer.kt
> +            val ociLoginAuthHandler = AWS4AuthHandler(authenticationManager)
`ociLoginAuthHandler`这里命名要改一下

2023-12-20 08:58 UTC, zacYL commented on src/backend/s3/biz-s3/src/main/kotlin/com/tencent/bkrepo/s3/artifact/S3LocalRepository.kt
> +        throw S3NotFoundException(
这里抛出异常不一定是 not found, 你这样会把其他异常吞掉

2023-12-20 09:03 UTC, cnlkl commented on src/backend/common/common-service/build.gradle.kts
> +    api("org.dom4j:dom4j:${Versions.Dom4j}")
这个依赖要移到S3模块

2023-12-28 02:18 UTC, zacYL approved these changes

2023-12-28 06:41 UTC, cnlkl approved these changes

2023-12-28 06:43 UTC, cnlkl commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/http/aws4/AWS4AuthHandler.kt
> +                var password: String? = authenticationManager.findUserPwd(userName)
在单独PR中修改

2023-12-28 06:50 UTC, merged