feat: Proxy支持删除未同步的文件存储 #1836
TencentBlueKing/bk-repo pull request #1847
Opened 2024-03-07 08:56 UTC by yaoxuwan

2024-03-08 04:17 UTC, cnlkl requested changes

2024-03-08 04:17 UTC, cnlkl commented on src/proxy/biz-proxy/src/main/kotlin/com/tencent/bkrepo/proxy/artifact/storage/ProxyStorageService.kt
> +            fileStorage.delete(path, syncFileName, proxyCredentials)
这里能不能直接覆盖写，避免出现删除成功，但是proxy进程挂掉未执行写入的情况

2024-03-08 04:17 UTC, cnlkl commented on src/proxy/biz-proxy/src/main/kotlin/com/tencent/bkrepo/proxy/artifact/storage/ProxyStorageService.kt
> +            val inputStream = IOUtils.toInputStream(credentials.key.toString(), Charset.defaultCharset())
这里文件已经同步成功也要再重新创建.sync文件吗

2024-03-08 08:19 UTC, yaoxuwan commented on src/proxy/biz-proxy/src/main/kotlin/com/tencent/bkrepo/proxy/artifact/storage/ProxyStorageService.kt
> +            val inputStream = IOUtils.toInputStream(credentials.key.toString(), Charset.defaultCharset())
同步成功的和新上传的不一定是同一个存储实例

2024-03-12 06:51 UTC, cnlkl approved these changes

2024-03-12 07:18 UTC, cnlkl commented on src/proxy/biz-proxy/src/main/kotlin/com/tencent/bkrepo/proxy/artifact/storage/ProxySyncFileVisitor.kt
> +        syncFile.delete()
blobPush执行失败时这里也会把sync文件删掉吗

2024-03-12 11:41 UTC, cnlkl approved these changes

2024-03-13 03:18 UTC, merged