feat:项目管理员可以在前端页面上查看对应节点下载记录 #1896
TencentBlueKing/bk-repo pull request #1982
Opened 2024-04-08 03:35 UTC by lannoy0523

2024-04-15 13:24 UTC, cnlkl requested changes

2024-04-15 13:29 UTC, zacYL commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
> +    private fun convertRecordDownloadRequest(userId: String, node: ArtifactInfo): GenericDownloadCreateRequest {
这个功能不是都应该从oplog里去查询记录吗？ 为什么还要改下载模块？

2024-04-16 01:14 UTC, lannoy0523 commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericRemoteRepository.kt
> +        recordDownload(context)
父类的写记录不是我想要的，父类的记录是带版本，sha那些的

2024-04-16 01:14 UTC, lannoy0523 commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +        recordDownload(context)
父类的写记录不是我想要的，父类的记录是带版本，sha那些的

2024-04-16 01:26 UTC, lannoy0523 commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/model/TGenericDownloadRecord.kt
> +data class TGenericDownloadRecord(
走切面的记录是无法感知下载成功。

2024-04-18 10:06 UTC, lannoy0523 commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/model/TGenericDownloadRecord.kt
> +data class TGenericDownloadRecord(
没注意看事件分发记录。

2024-05-28 09:33 UTC, zacYL commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/imp/GenericDownloadRecordServiceImp.kt
> +        with(genericPageRequest) {
这个日志是按月分表的，这样查询数据能查全吗

2024-05-31 12:18 UTC, cnlkl requested changes

2024-06-03 03:08 UTC, closed without merging