bug: 限制admin修改 #2115
TencentBlueKing/bk-repo pull request #2121
Opened 2024-05-08 07:38 UTC by owenlxu

2024-05-09 04:15 UTC, cnlkl approved these changes

2024-05-09 04:15 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/interceptor/AuthInterceptor.kt
>              AUTH_API_OAUTH_PREFIX,
`OauthAuthorizationController`和`ExternalPermissionController`存在未鉴权接口

2024-05-09 04:16 UTC, cnlkl requested changes

2024-05-09 04:16 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/interceptor/AuthInterceptor.kt
>          val userAccess = userAccessApiSet.any { request.requestURI.contains(it) }
`request.requestURI.contains`这里使用`contains`而不是`startsWith`会不会导致放通预期外的接口

2024-05-09 07:00 UTC, owenlxu commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/interceptor/AuthInterceptor.kt
>              AUTH_API_OAUTH_PREFIX,
已确认

2024-05-09 07:00 UTC, owenlxu commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/interceptor/AuthInterceptor.kt
>          val userAccess = userAccessApiSet.any { request.requestURI.contains(it) }
已修改

2024-05-09 08:19 UTC, zacYL commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/user/RoleController.kt
>          return ResponseBuilder.success(roleService.detail(id))
这里可以直接返回role，不用再查询一次了

2024-05-09 08:20 UTC, zacYL commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/user/RoleController.kt
>          return ResponseBuilder.success(roleService.detail(id))
这里可以直接返回role，不用再查询一次了

2024-05-09 12:14 UTC, cnlkl submitted a review, later dismissed

2024-05-09 12:29 UTC, owenlxu commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/user/RoleController.kt
>          return ResponseBuilder.success(roleService.detail(id))
已修改

2024-05-09 12:30 UTC, zacYL submitted a review, later dismissed

2024-05-10 06:44 UTC, zacYL approved these changes

2024-05-10 07:07 UTC, merged