feat: 支持仓库关闭默认权限 #2164
TencentBlueKing/bk-repo pull request #2180
Opened 2024-05-23 13:39 UTC by owenlxu

2024-05-27 12:20 UTC, cnlkl requested changes

2024-05-27 13:49 UTC, owenlxu commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/service/ServicePermissionController.kt
> +            if (permissionPath == null) {
根据status来，status为true需要处理

2024-05-28 02:31 UTC, zacYL commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/local/PermissionServiceImpl.kt
> +        if (personalPath != null) {
这里没有去重

2024-05-28 02:36 UTC, cnlkl approved these changes

2024-05-28 02:59 UTC, zacYL approved these changes

2024-05-28 03:14 UTC, merged