feat: 支持配置NPM返回的下载路径是否包含仓库ID #2498
TencentBlueKing/bk-repo pull request #2505
Opened 2024-08-20 08:01 UTC by cnlkl

1. #2498
2. #1140

2024-08-20 09:11 UTC, zacYL approved these changes

2024-08-20 10:46 UTC, scplsy requested changes

2024-08-20 10:46 UTC, scplsy commented on src/backend/npm/biz-npm/src/main/kotlin/com/tencent/bkrepo/npm/utils/NpmUtils.kt
> +                newTarball.append(SLASH).append(artifactInfo.getRepoIdentify())
这里会产生2个连续的`/`

2024-08-21 08:53 UTC, scplsy approved these changes

2024-08-21 09:14 UTC, merged