feat: 大文件下载优化 #2656
TencentBlueKing/bk-repo pull request #2665
Opened 2024-10-17 02:15 UTC by felixncheng

2024-10-17 08:16 UTC, cnlkl requested changes

2024-10-17 08:16 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        return FileSystemClient(getChunksPath(credentials))
要不要放到cache目录中兼容保留策略，方便统一管理

2024-10-17 08:16 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +                inputStream.use { it.drain() }
这里为什么要先写到文件中再从文件中读流返回给用户，不能一次读流分别写给用户和缓存文件吗

2024-10-17 08:23 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/test/resources/storage-cache-fs.properties
> +storage.filesystem.cache.largeFileOptimization=true
要不要改成只在`largeFileOptimizationTest`中开启，避免影响现有测试

2024-10-17 10:08 UTC, felixncheng commented on src/backend/common/common-storage/storage-api/src/main/kotlin/com/tencent/bkrepo/common/storage/config/CacheProperties.kt
> +    var largeFileSizeThreshold: DataSize = DataSize.ofMegabytes(8),
目前看这两个值是一样的，所以采用一个参数了。

2024-10-17 10:09 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        private val ioThreadPool =
跟用户io 1:1的，所以线程数是有限的

2024-10-17 10:11 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +                val inputStream = preFetchFuture?.get(CHUNK_DOWNLOAD_TIMEOUT, TimeUnit.SECONDS)
这里的块比cos的小，所以这里没用到cos的分块功能。

2024-10-17 10:12 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        return FileSystemClient(getChunksPath(credentials))
一开始是这么考虑的，但是cache中的文件名都被当做sha256来用了，所以只能另外单独一个目录。

2024-10-17 10:13 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +                inputStream.use { it.drain() }
异步缓存效率比透传高，如果客户端读的速度慢或者读一半中断了，不会影响到分片的缓存

2024-10-17 10:15 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/test/resources/storage-cache-fs.properties
> +storage.filesystem.cache.largeFileOptimization=true
这个选项是优化大文件下载，不会影响下载的本身行为，如果有影响就代表这个功能有问题了。

2024-10-17 10:16 UTC, cnlkl approved these changes

2024-10-17 12:12 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        private val ioThreadPool =
看起来开启分片缓存时只支持单连接下载，能不能不使用线程池

2024-10-17 12:21 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +                val inputStream = preFetchFuture?.get(CHUNK_DOWNLOAD_TIMEOUT, TimeUnit.SECONDS)
两个分块大小都是可配置的

2024-10-17 12:27 UTC, cnlkl commented
这个修改会导致用户单连接下载时无法触发制品库后端分片下载，可能需要引导用户使用下载工具多连接下载

2024-10-17 13:09 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +                inputStream.use { it.drain() }
会增加一次读缓存操作，可能会导致缓存盘io或带宽占用上升

2024-10-18 02:04 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        return FileSystemClient(getChunksPath(credentials))
需要修改主动淘汰策略支持淘汰分片缓存

2024-10-18 02:22 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        val total = range.total ?: return false
目前只有archive中存在不知道文件大小的情况下需要下载文件。

2024-10-18 02:23 UTC, cnlkl commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        return FileSystemClient(getChunksPath(credentials))
需要修改`deleteCacheFile`与`doDelete`方法同时删除分片缓存

2024-10-18 02:28 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/main/kotlin/com/tencent/bkrepo/common/storage/core/cache/CacheStorageService.kt
> +        return FileSystemClient(getChunksPath(credentials))
是的，这里需要重新优化监控了。现有的缓存管理比较复杂，需要优化的更加简单点。

2024-10-18 02:34 UTC, felixncheng commented on src/backend/common/common-storage/storage-service/src/test/resources/storage-cache-fs.properties
> +storage.filesystem.cache.largeFileOptimization=true
单侧覆盖缺失，也就是实际运行时也不会运行到那里去了。如果测试通过，则表明不影响，反之表示该功能的引入会对其他功能产生影响。

2024-10-18 02:37 UTC, felixncheng commented
> 这个修改会导致用户单连接下载时无法触发制品库后端分片下载，可能需要引导用户使用下载工具多连接下载

是的，也考虑是否要放开原有的分片下载，但是考虑到原有的大文件分片下载并不会进行缓存且在高峰时也会降级到普通下载，所以还是现有的大文件下载更好些。

2024-10-18 02:54 UTC, felixncheng commented
https://github.com/TencentBlueKing/bk-repo/issues/2667 由于增加一个分片缓存目录，现有的监控与清理逻辑需要相应修改，由于现有的代码已经比较复杂，所以另外提了个issue来优化这快内容

2024-10-18 03:00 UTC, cnlkl commented
> > 这个修改会导致用户单连接下载时无法触发制品库后端分片下载，可能需要引导用户使用下载工具多连接下载
> 
> 是的，也考虑是否要放开原有的分片下载，但是考虑到原有的大文件分片下载并不会进行缓存且在高峰时也会降级到普通下载，所以还是现有的大文件下载更好些。

可以结合起来，现在是只会提前下载下一个分片，如果提前并发下载多个分片到缓存就可以提升单连接下载速度

2024-10-18 03:25 UTC, felixncheng commented
> > > 这个修改会导致用户单连接下载时无法触发制品库后端分片下载，可能需要引导用户使用下载工具多连接下载
> > 
> > 
> > 是的，也考虑是否要放开原有的分片下载，但是考虑到原有的大文件分片下载并不会进行缓存且在高峰时也会降级到普通下载，所以还是现有的大文件下载更好些。
> 
> 可以结合起来，现在是只会提前下载下一个分片，如果提前并发下载多个分片到缓存就可以提升单连接下载速度

从服务端考虑，更关心吞吐和稳定性，为了提高单连接的速度，采用后台1:n的模式下载，会增加回源压力。另外提前下载多个分片，用户可能也不会读取，比如下载取消或者中断。所以综上所诉，如果用户追求下载速度，建议分片下载。

另外说一下，我们这里所说的单连接速度慢，实际上是某个存储数据源慢，如果数据源本身不会限速，就更不必要后台主动1:n分片下载了。所以代码设计上，更加考虑通用性，而不是针对某一个特殊的数据源，写特殊逻辑，这是我的看法。

2024-10-18 04:01 UTC, cnlkl commented
> > > > 这个修改会导致用户单连接下载时无法触发制品库后端分片下载，可能需要引导用户使用下载工具多连接下载
> > > 
> > > 
> > > 是的，也考虑是否要放开原有的分片下载，但是考虑到原有的大文件分片下载并不会进行缓存且在高峰时也会降级到普通下载，所以还是现有的大文件下载更好些。
> > 
> > 
> > 可以结合起来，现在是只会提前下载下一个分片，如果提前并发下载多个分片到缓存就可以提升单连接下载速度
> 
> 从服务端考虑，更关心吞吐和稳定性，为了提高单连接的速度，采用后台1:n的模式下载，会增加服务器和存储数据源压力。另外提前下载多个分片，用户可能也不会读取，比如下载取消或者中断。所以综上所诉，如果用户追求下载速度，建议分片下载。
> 

之前CosClient是出于什么考虑支持后台分片下载的，现在可以禁用这个功能，或移除这部分代码，然后统一建议用户客户端分片下载吗

2024-10-18 04:08 UTC, felixncheng commented
> > > > > 这个修改会导致用户单连接下载时无法触发制品库后端分片下载，可能需要引导用户使用下载工具多连接下载
> > > > 
> > > > 
> > > > 是的，也考虑是否要放开原有的分片下载，但是考虑到原有的大文件分片下载并不会进行缓存且在高峰时也会降级到普通下载，所以还是现有的大文件下载更好些。
> > > 
> > > 
> > > 可以结合起来，现在是只会提前下载下一个分片，如果提前并发下载多个分片到缓存就可以提升单连接下载速度
> > 
> > 
> > 从服务端考虑，更关心吞吐和稳定性，为了提高单连接的速度，采用后台1:n的模式下载，会增加服务器和存储数据源压力。另外提前下载多个分片，用户可能也不会读取，比如下载取消或者中断。所以综上所诉，如果用户追求下载速度，建议分片下载。
> 
> 之前CosClient是出于什么考虑支持后台分片下载的，现在可以禁用这个功能，或移除这部分代码，然后统一建议用户客户端分片下载吗

之前是会了提高单连接的速度，这个功能还是有必要存在的，cos下载提速不仅仅用在供用户客户端下载，我们自己也会作为客户端，从cos上下载，这个时候cos分片下载就起作用了。

2025-08-22 07:10 UTC, closed without merging