fix: 制品分析的方案详情页的许可证总数取值不正确,当许可证总数为0时会显示漏洞总数的数据#374
TencentBlueKing/bk-repo pull request #375
Opened 2023-04-03 06:51 UTC by gujunling

fix: 制品分析的方案详情页的许可证总数取值不正确,当许可证总数为0时会显示漏洞总数的数据

2023-04-04 02:22 UTC, cnlkl requested changes

2023-04-04 02:22 UTC, cnlkl commented on src/frontend/devops-repository/src/views/repoScan/scanReport/overview.vue
> -                            this.overview[key] = planCount[key] || this.overview[key]
这边如果许可总数和漏洞总数都非0会有覆盖的情况，这里可能要把key区分下，或者许可和漏洞用两个overview变量 #281

2023-04-04 03:55 UTC, gujunling commented on src/frontend/devops-repository/src/views/repoScan/scanReport/overview.vue
> -                            this.overview[key] = planCount[key] || this.overview[key]
应该不用吧，现在只显示了许可证的总数，漏洞总数没有显示，而且漏洞总数也没有key

2023-04-04 06:40 UTC, cnlkl approved these changes

2023-04-04 06:41 UTC, cnlkl approved these changes

2023-04-06 06:30 UTC, owenlxu approved these changes

2023-04-06 09:18 UTC, merged