feat: 自动创建release分支 #252
TencentBlueKing/bk-repo pull request #481
Opened 2023-04-24 10:07 UTC by felixncheng

2023-05-11 02:58 UTC, cnlkl requested changes

2023-05-11 02:58 UTC, cnlkl commented on .github/workflows/release.yml
> +          git config user.email "bkrepo-project-bot@users.noreply.github.com"
现在没有bkrepo机器人，要不要改成bk-ci机器人的

2023-05-11 03:25 UTC, felixncheng commented on .github/workflows/release.yml
> +          git config user.email "bkrepo-project-bot@users.noreply.github.com"
这只是个虚拟账号，永远不会有回复的。

2023-05-15 03:33 UTC, felixncheng commented on .github/workflows/release.yml
> +          git config user.email "bkrepo-project-bot@users.noreply.github.com"
经讨论，决定还是使用bk-ci bot。已修改为bk-ci bot

2023-05-15 04:07 UTC, cnlkl approved these changes

2023-05-16 02:15 UTC, merged