feat: 权限中心v3-rbac模式下没权限跳转连接需要新开窗口 #554
TencentBlueKing/bk-repo pull request #579
Opened 2023-05-15 02:06 UTC by lannoy0523

2023-05-16 03:09 UTC, zacYL approved these changes

2023-05-16 03:17 UTC, cnlkl requested changes

2023-05-16 03:17 UTC, cnlkl commented on src/frontend/devops-repository/src/components/IamDenyDialog/IamDenyDialog.vue
> +            <bk-button @click="open">{ $t('apply') }</bk-button>
这里缺少`{}`

2023-05-17 02:21 UTC, cnlkl approved these changes

2023-05-18 11:42 UTC, merged