feat: proxy上传、下载接口 #705
TencentBlueKing/bk-repo pull request #765
Opened 2023-06-09 11:57 UTC by yaoxuwan

2023-06-12 08:16 UTC, felixncheng commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/util/HttpSigner.kt
> +    const val PROXY_NAME = "proxy_name"
这个好像与签名算法无关？

2023-06-12 14:53 UTC, cnlkl requested changes

2023-06-12 14:53 UTC, cnlkl commented on src/backend/auth/api-auth/src/main/kotlin/com/tencent/bkrepo/auth/api/proxy/ProxyOauthAuthorizationClient.kt
> +@RequestMapping("/proxy/oath")
拼写错误oauth

2023-06-12 14:53 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/proxy/ProxyUserController.kt
> +    override fun createUser(request: CreateUserRequest): Response<Boolean> {
这个Controller的接口都缺少鉴权

2023-06-12 14:53 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/proxy/ProxyAccountController.kt
> +        val result = accountService.findSecretKey(appId, accessKey)
缺少鉴权

2023-06-12 14:53 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/service/ServiceProxyController.kt
> +) : ServiceProxyClient {
proxy调auth不应该通过微服务接口调用

2023-06-12 14:53 UTC, cnlkl commented on src/backend/common/common-artifact/artifact-service/src/main/kotlin/com/tencent/bkrepo/common/artifact/repository/context/ArtifactContextHolder.kt
> +        private fun getRepositoryDetailOrNull(
可以把这块内容抽离成一个单独的类，proxy提供不同实现，而不是通过if-else判断应用名进行区分

2023-06-12 14:53 UTC, cnlkl commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/SecurityAutoConfiguration.kt
> +    @ConditionalOnExpression("'\${spring.application.name}' != 'proxy'")
这边可以这里提供默认实现，然后加上ConditionalOnMissingBean，proxyAuthenticationManager仅在proxy模块中提供

2023-06-12 14:53 UTC, cnlkl commented on src/backend/common/common-security/src/main/kotlin/com/tencent/bkrepo/common/security/proxy/ProxyAuthInterceptor.kt
>          request.getHeader(MS_AUTH_HEADER_UID)?.let {
此处是否存在伪装成任意用户的风险

2023-06-12 14:53 UTC, cnlkl commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/proxy/ProxyFeignClientFactory.kt
> +//        val url = FeignClientFactory.normalizeUrl(gateway, serviceName)
gateway未使用

2023-06-12 14:53 UTC, cnlkl commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/service/ProxyService.kt
> +        permissionManager.checkProjectPermission(PermissionAction.READ, projectId)
这边返回的proxyJar包含了secretKey，仅验证读权限是否存在提权的风险

2023-06-12 14:53 UTC, cnlkl commented on src/backend/generic/boot-generic/build.gradle.kts
> +project(":generic:boot-generic") {
这边在把proxy.jar打包到generic服务中是否会导致generic服务包体积变大不利于分发，能不能在运行过程中从一个固定位置拉取，这样也容易更新，否则要更新proxy就要同时更新generic服务

2023-06-12 14:53 UTC, cnlkl commented on src/backend/proxy/boot-proxy/src/main/resources/.proxy.properties
> +bkrepo.proxy.project.id=yaoxuwan
敏感信息需要移除

2023-06-12 14:53 UTC, cnlkl commented on src/backend/repository/biz-repository/src/main/kotlin/com/tencent/bkrepo/repository/controller/proxy/ProxyRepositoryController.kt
> +        return ResponseBuilder.success(repositoryService.getRepoDetail(projectId, repoName, type))
缺少鉴权

2023-06-12 14:53 UTC, cnlkl commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/service/impl/ProxyServiceImpl.kt
> +        return ProxyKey(tProxy.secretKey, tProxy.sessionKey)
secretKey，sessionKey，ticket的生成未使用安全随机数，可预测存在安全风险

2023-06-13 06:31 UTC, yaoxuwan commented on src/backend/auth/biz-auth/src/main/kotlin/com/tencent/bkrepo/auth/controller/service/ServiceProxyController.kt
> +) : ServiceProxyClient {
这个接口不是proxy调用的，是服务认证proxy的请求时调用的

2023-06-13 08:00 UTC, yaoxuwan commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/util/HttpSigner.kt
> +    const val PROXY_NAME = "proxy_name"
ProxyAuthInterceptor中需要根据proxy_name查询对应密钥，验证签名

2023-06-13 11:32 UTC, zacYL commented on src/backend/common/common-api/src/main/kotlin/com/tencent/bkrepo/common/api/util/UrlFormatter.kt
> -package com.tencent.bkrepo.common.artifact.util.http
插件等是否有引用

2023-07-25 06:41 UTC, cnlkl approved these changes

2023-08-16 06:36 UTC, merged