feat: 一次性分发任务支持按照配置的规则选择特定的机器执行 TencentBlueKing#780
TencentBlueKing/bk-repo pull request #784
Opened 2023-06-13 08:47 UTC by zacYL

2023-06-15 08:49 UTC, felixncheng approved these changes

2023-06-15 09:22 UTC, cnlkl requested changes

2023-06-15 09:22 UTC, cnlkl commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +    private fun <T> findReplicaClientByRuleIndex(ruleInfo: ReplicaNodeDispatchRuleInfo, target: Class<T>): T? {
这个方法传了`ruleInfo`进来，又到数据库中查出来configs，configs里也定义了规则，但实际上只取configs里的值，而忽略了configs里的规则

是不是直接通过config构造出一个rule比较合适

2023-06-15 09:22 UTC, cnlkl commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +            if (selfNode(filterConfig.nodeUrl)) return null
判断是否是自身节点是不是在实际执行分发的方法里去做比较好，这边就只负责规则匹配

最好创建client也单独作为一个方法，和规则匹配分开，单一职责

2023-06-15 09:22 UTC, cnlkl commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +                    val configs = getReplicaNodeDispatchConfig(ruleIndex.value, ruleType)
这里如果规则定义了IN和EQ，就只有一种能生效了，如果创建EQ规则这里就会不生效

2023-06-15 09:22 UTC, cnlkl commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +                        RuleMatcher.match(rule, mapOf(ruleIndex.value to it.value))
这边用于匹配的值反了，应该是`RuleMatcher.match(configToRule, mapOf(ruleInfo.value))`

2023-06-15 09:22 UTC, cnlkl commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +        if (nodeUrl.contains("$LOCAL_HOST${StringPool.COLON}")) {
这边是不是把host作为参数传进来对比会好点，不然`localhost.bkrepo.example.com`这种域名也会返回true

2023-06-15 09:22 UTC, cnlkl commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +            val value: Any = when (ruleType) {
为什么value要到这里做转换，`ReplicaNodeDispatchRuleInfo`数据结构定义是不是有问题，如果`ruleType`是IN，`ruleValue`也是`String`

2023-06-15 09:40 UTC, cnlkl commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/feign/FeignClientFactory.kt
> +        normalizeUrl: Boolean = true
`normalizeUrl`这里为什么要加上这个参数，调用远程节点的一次性任务分发接口和原来replication服务的接口调用逻辑不是一样的吗

2023-06-15 15:03 UTC, zacYL commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/model/TReplicaNodeDispatchConfig.kt
> +    var ruleType: OperationType,
已修改

2023-06-15 15:03 UTC, zacYL commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/ReplicaNodeDispatchServiceImpl.kt
> +                    val configs = getReplicaNodeDispatchConfig(ruleIndex.value, ruleType)
已修改成动态

2023-06-15 15:04 UTC, zacYL commented on src/backend/replication/biz-replication/src/main/kotlin/com/tencent/bkrepo/replication/service/impl/RemoteNodeServiceImpl.kt
> +    override fun executeRunOnceTask(projectId: String, repoName: String, name: String, dispatch: Boolean) {
dispatch参数避免fegin调用后还再次进行配置判断

2023-06-15 15:05 UTC, zacYL commented on src/backend/common/common-service/src/main/kotlin/com/tencent/bkrepo/common/service/feign/FeignClientFactory.kt
> +        normalizeUrl: Boolean = true
ip+port已经包含对应服务名，不需要再次添加

2023-06-16 03:03 UTC, cnlkl approved these changes

2023-06-16 03:17 UTC, merged