feature: 制品分析的扫描报告和制品漏洞报告导出 #830
TencentBlueKing/bk-repo pull request #831
Opened 2023-06-20 08:42 UTC by SunnyShen434

What would you like to be added:
1. 扫描任务状态添加UN_QUALITY、QUALITY_PASS、QUALITY_UNPASS, 以便于扫描报告导出; 并同步其他扫描任务状态的处理逻辑
2. 制品分析的扫描报告导出
3. 制品分析的制品漏洞报告导出
4. 修复函数命名错误: createProjectIdAdnRepoRule -> createProjectIdAndRepoRule
5. 之前代码提交不完整, 补充修复: 删除仓库后查看制品扫描记录鉴权异常

Why is this needed:
作为制品库管理员, 需要查看安全扫描报告, 以便于做数据统计与汇报

2023-06-20 08:42 UTC, tencentblueking-adm commented
[![CLA assistant check](https://bk-cla.bktencent.com:443/pull/badge/not_signed)](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-repo?pullRequest=831) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bk-cla.bktencent.com:443/TencentBlueKing/bk-repo?pullRequest=831) before we can accept your contribution.<br/><hr/>**xiaoyushen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bk-cla.bktencent.com:443/check/TencentBlueKing/bk-repo?pullRequest=831) it.</sub>

2023-06-20 13:07 UTC, cnlkl requested changes

2023-06-25 13:06 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/user/UserScanReportController.kt
> +    @GetMapping("/export/artifact/leak/{projectId}/{subScanTaskId}")
此接口与`/artifact/leak/{projectId}/{subScanTaskId}`接口类似, 都调用`fun resultDetail(request: ArtifactVulnerabilityRequest): Page<ArtifactVulnerabilityInfo>`函数, 那里面已做鉴权, 不再重复鉴权

2023-06-26 04:06 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
> +            val isLicenseScan = scanPlan.type.endsWith("_LICENSE")
已修改, 感谢指正

2023-06-27 03:14 UTC, cnlkl requested changes

2023-06-27 03:14 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/ScanLicenseConverter.kt
> +                qualityRedLine = qualityRedLine?.let { if (it) "通过" else "不通过" } ?: "/",
可以考虑用`LocaleMessageUtils`获取`通过` `不通过`的文案

2023-06-27 03:18 UTC, cnlkl commented
#471

2023-06-30 09:24 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
> +            request.pageNumber = ++pageNumber
已在`planArtifactLatestSubScanTaskDao`中添加一个`获取指定扫描方案的制品最新扫描记录`的方法, 感谢指正

2023-07-03 08:32 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/utils/ScanLicenseConverter.kt
> +                qualityRedLine = qualityRedLine?.let { if (it) "通过" else "不通过" } ?: "/",
考虑到前后端一致性, 需要删除`qualityRedLine`字段, 使用`status`导出为扫描状态`ScanStatus`;
已修改为用`LocaleMessageUtils`获取8种扫描状态的文案. 感谢指正

2023-07-07 08:54 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
> +        } catch (e: UncheckedExecutionException) {
这里什么情况会抛出`UncheckedExecutionException`

2023-07-08 06:02 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanTaskServiceImpl.kt
> +        } catch (e: UncheckedExecutionException) {
获取许可扫描子任务信息 的时候会抛`UncheckedExecutionException`, 但是现在版本已经没有在使用这个函数相关的接口, 所以代码无需改动
已移除, 感谢指正!

2023-07-10 02:51 UTC, cnlkl approved these changes

2023-07-10 06:32 UTC, cnlkl approved these changes

2023-07-11 02:15 UTC, cnlkl approved these changes

2023-07-11 02:16 UTC, merged