feat: 批量下载支持目录节点 #778
TencentBlueKing/bk-repo pull request #884
Opened 2023-07-04 05:04 UTC by scplsy

issue #778

1. batchDownload新增POST请求类型（前端GET请求无法发送请求体）。
2. 可以同时选择文件和目录节点，空目录也会一同下载。
3. 修复了下载多个节点时，公共目录层数过多的问题。

2023-07-06 08:18 UTC, yaoxuwan commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +            }
先检查数量，再查询子节点，可能会下载的文件太多

2023-07-06 08:29 UTC, yaoxuwan commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +            // 检查文件大小总和, 下载拦截
检查文件数量会多次查询子节点数量，添加目录节点的子节点数还会查询多次。目录多的情况会有大量重复查询

2023-07-07 07:16 UTC, scplsy commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +            // 检查文件大小总和, 下载拦截
已优化

2023-07-07 07:57 UTC, cnlkl requested changes

2023-07-07 07:57 UTC, cnlkl commented on src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/node/NodeListOption.kt
> +    var pageNumber: Int = DEFAULT_PAGE_NUMBER,
可以用copy方法创建一个新的，不要改变原来的值

2023-07-07 07:57 UTC, cnlkl commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +            val prefixToAdd = if (PathUtils.isRoot(commonParent) && fullPathList.size > 1) "$repoName/" else ""
这边注释加一下示例说明`prefixToAdd`和`prefixToRemove`的作用

2023-07-10 06:05 UTC, scplsy commented on src/backend/repository/api-repository/src/main/kotlin/com/tencent/bkrepo/repository/pojo/node/NodeListOption.kt
> +    var pageNumber: Int = DEFAULT_PAGE_NUMBER,
已处理

2023-07-10 06:05 UTC, scplsy commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +            val prefixToAdd = if (PathUtils.isRoot(commonParent) && fullPathList.size > 1) "$repoName/" else ""
已加注释

2023-07-11 03:03 UTC, yaoxuwan commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
>          checkFileCount(node)
下载单个目录是检查文件数量的步骤需要移至获取子节点后

2023-07-11 03:31 UTC, yaoxuwan commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +                nodes.addAll(records.map { NodeDetail(it) })
循环时可以提前判断节点数量

2023-07-11 13:37 UTC, scplsy commented on src/backend/generic/biz-generic/src/main/kotlin/com/tencent/bkrepo/generic/artifact/GenericLocalRepository.kt
> +                nodes.addAll(records.map { NodeDetail(it) })
已优化

2023-07-12 02:06 UTC, yaoxuwan approved these changes

2023-07-12 06:41 UTC, cnlkl approved these changes

2023-07-12 06:42 UTC, merged