制品分析的扫描方案增加质量规则开关
TencentBlueKing/bk-repo pull request #979
Opened 2023-07-20 13:03 UTC by SunnyShen434

#921

2023-07-25 07:43 UTC, cnlkl requested changes

2023-07-25 07:43 UTC, cnlkl commented on src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/ScanQuality.kt
> +            forbidScanUnFinished = map[ScanQuality::forbidScanUnFinished.name] as? Boolean,
这里为什么要移除默认值`false`

2023-07-25 07:43 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/FinishSubtaskAction.kt
> +        val qualityPass = if (subTask.scanQuality.isNullOrEmpty() || planId == null) {
这边能不能只判断`subTask.scanQuality.isNullOrEmpty()`这个条件

2023-07-25 12:31 UTC, SunnyShen434 commented on docs/apidoc/scanner/scan-quality.md
> +| planId | string | 是    | 无   | 方案id | plan id     |
抱歉, 漏掉了, 已补上

2023-07-25 12:51 UTC, SunnyShen434 commented on src/backend/analyst/api-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/pojo/response/ScanQuality.kt
> +            forbidScanUnFinished = map[ScanQuality::forbidScanUnFinished.name] as? Boolean,
`ScanQuality`为`{}`时前端显示质量规则关, 不为`{}`时显示开. 
如果有默认值`false`, 前端会一直显示质量规则开

2023-07-25 13:04 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/statemachine/subtask/action/FinishSubtaskAction.kt
> +        val qualityPass = if (subTask.scanQuality.isNullOrEmpty() || planId == null) {
`subTask.planId`可能为`null`, 如果不在这里判断, 也得在`scanQualityService.checkScanQualityRedLine`里判断, 感觉还是这里判断比较好. 
原来也是在这里判断的, 不知道我有理解到你说的意思吗?

2023-07-28 06:52 UTC, cnlkl requested changes

2023-07-28 06:52 UTC, cnlkl commented on docs/apidoc/scanner/scan-quality.md
> +- API: post /analyst/api/scan/quality
api路径漏了/{planId}

2023-07-29 07:44 UTC, SunnyShen434 commented on docs/apidoc/scanner/scan-quality.md
> +- API: post /analyst/api/scan/quality
已补充, 感谢指正

2023-07-31 01:57 UTC, cnlkl approved these changes

2023-07-31 11:49 UTC, merged