fix: 后端适配前端展示制品分析成功状态 #471
TencentBlueKing/bk-repo pull request #980
Opened 2023-07-20 13:08 UTC by SunnyShen434

#471

2023-07-20 13:13 UTC, SunnyShen434 commented
`ScanPlanService`的`artifactPlanStatu`函数已不再使用, 所以不校验权限也可以, 合并过来为了使两边代码保持统一

2023-07-21 12:42 UTC, cnlkl requested changes

2023-07-21 12:42 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/user/UserScanPlanController.kt
> +    ): Response<Map<String, Any?>> {
这边可以定义个具体类型作为返回值而不是用Map

2023-07-21 12:42 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
>      override fun artifactPlanStatus(request: ArtifactPlanRelationRequest): String? {
未使用的函数可以删除

2023-07-21 12:42 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> +                    ?: throw NotFoundException(CommonMessageCode.RESOURCE_NOT_FOUND, packageKey!!, version!!)
这边只要fullPath为null就要抛NotFound异常
```kotlin
val packageVersion = Request.request {
    packageClient.findVersionByName(projectId, repoName, packageKey!!, version!!)
}

fullPath = packageVersion?.contentPath ?: packageVersion?.manifestPath
fullPath ?: throw NotFoundException(CommonMessageCode.RESOURCE_NOT_FOUND, packageKey!!, version!!)

```

2023-07-21 12:42 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> +        checkPermission: Boolean
可以把checkPermission参数移除

2023-07-24 01:57 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
>      override fun artifactPlanStatus(request: ArtifactPlanRelationRequest): String? {
已删除, 感谢指正

2023-07-24 02:11 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/controller/user/UserScanPlanController.kt
> +    ): Response<Map<String, Any?>> {
已封装, 感谢指正

2023-07-24 02:26 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> +        checkPermission: Boolean
已移除, 感谢指正

2023-07-24 05:55 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> +                    ?: throw NotFoundException(CommonMessageCode.RESOURCE_NOT_FOUND, packageKey!!, version!!)
改为如果`contentPath`为null再判断`manifestPath`是为了兼容, 嘉为这边目前还是使用的docker服务, 没有使用oci服务. docker服务存储版本信息的时候会自己去构建请求, `contentPath`为null; 而oci服务存储时调用的公共update方法, `contentPath`和`manifestPath`都赋了同一个值. 

看下腾讯是否需要这个兼容? 无需的话这里可以不改

2023-07-25 09:35 UTC, cnlkl requested changes

2023-07-25 09:35 UTC, cnlkl commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> +                    ?: throw NotFoundException(CommonMessageCode.RESOURCE_NOT_FOUND, packageKey!!, version!!)
`Request.request {packageClient.findVersionByName(projectId, repoName, packageKey!!, version!!)}`
和兼容oci或docker没有关系，上面这个请求是可能返回`null`的，你这样写在请求返回null的时候不会抛异常

2023-07-25 11:32 UTC, SunnyShen434 commented on src/backend/analyst/biz-analyst/src/main/kotlin/com/tencent/bkrepo/analyst/service/impl/ScanPlanServiceImpl.kt
> +                    ?: throw NotFoundException(CommonMessageCode.RESOURCE_NOT_FOUND, packageKey!!, version!!)
抱歉, 一开始没看出来, 理解错了, 已按照原来的修改

2023-07-26 02:26 UTC, cnlkl approved these changes

2023-07-28 09:50 UTC, merged