feat: 新增git lfs仓库 #964
TencentBlueKing/bk-repo pull request #988
Opened 2023-07-21 12:53 UTC by yaoxuwan

2023-08-02 03:08 UTC, yaoxuwan commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/artifact/LfsRemoteRepository.kt
> +        private const val LFS_USER_AGENT = "git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)"
不加agent，接口会返回403

2023-08-02 08:13 UTC, felixncheng commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/artifact/LfsRemoteRepository.kt
> +        private const val LFS_USER_AGENT = "git-lfs/3.3.0 (GitHub; windows amd64; go 1.19.3; git 77deabdf)"
agent的名称为什么是windows amd64; go 1.19.3...,不可以是以制品库命名一个agent吗

2023-08-02 09:11 UTC, cnlkl requested changes

2023-08-02 09:55 UTC, yaoxuwan commented on src/backend/lfs/biz-lfs/src/main/kotlin/com/tencent/bkrepo/lfs/artifact/LfsArtifactInfo.kt
> +    userId: String,
已修改

2023-08-03 06:55 UTC, cnlkl approved these changes

2023-08-03 07:10 UTC, merged